# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 15:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0004_auto_20160819_1043'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appointment',
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
