# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0009_appointment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='task_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='task_time',
            field=models.CharField(max_length=100),
        ),
    ]
