# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0011_remove_appointment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='login_registration.User'),
            preserve_default=False,
        ),
    ]
