# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0012_appointment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user_id',
        ),
    ]
