# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0013_remove_appointment_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
