# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='email',
            name='description',
        ),
        migrations.AddField(
            model_name='email',
            name='email_address',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
